const requiredEnvVars = [
  'MONGO_USER',
  'MONGO_PASS',
  'EMAIL_PASS',
  'EMAIL_USER',
  'AWS_ACCESS_KEY_PP',
  'AWS_SECRET_KEY_PP',
  'AWS_REGION_PP',
  'AWS_BUCKET_NAME_PP',
  'AWS_BUCKET_NAME_PDF',
  'AWS_BUCKET_NAME_PUBP',

  'STRIPE_SECRET_KEY',
  'VITE_STRIPE_PUBLISHABLE_KEY',
  'CLERK_SECRET_KEY',
  'CLERK_PUBLISHABLE_KEY',
  'VITE_CLERK_PUBLISHABLE_KEY',

  'SMTP_HOST',
  'SMTP_PORT',
  'SMTP_USER',
  'SMTP_PASS',

  'SMTP_FROM_NAME',
  'SMTP_FROM_EMAIL',

  'AWS_SES_ACCES_KEY',
  'AWS_SES_SECRET_KEY',
  'AWS_REGION_SES',

  'REDIS_URL',
  'BREVO_API_KEY',
  'BREVO_TEMPLATE_WELCOME',

  'BREVO_TEMPLATE_REGISTRATION_ACCEPTED',
  'BREVO_TEMPLATE_PAYMENT_REMINDER_DAY3',
  'BREVO_TEMPLATE_PAYMENT_REMINDER_DAY6',
  'BREVO_TEMPLATE_PAYMENT_CONFIRMED',
  'BREVO_TEMPLATE_REGISTRATION_CANCELLED',

  'PAYMENT_DEADLINE_DAYS',
  'PAYMENT_REMINDER_DAY3',
  'PAYMENT_REMINDER_DAY6',

  'BACKEND_URL',
  'EMAIL_PROCESSING_INTERVAL',
  'MAX_EMAIL_RETRIES'
];

export function validateEnv() {
    if (process.env.NODE_ENV === 'test') {
    return; 
  }
  const missing = requiredEnvVars.filter(
    (key) => !process.env[key]
  );

  if (missing.length > 0) {
    console.error('Missing environment variables:', missing);
    process.exit(1);
  }
}
